import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                //css
                "resources/css/app.css",
                "resources/assets/vendor/css/core.css",
                "resources/assets/css/demo.css",
                "resources/assets/vendor/fonts/iconify-icons.css",
                "resources/assets/vendor/libs/node-waves/node-waves.css",
                "resources/assets/vendor/libs/pickr/pickr-themes.css",

                "resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css",
                "resources/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css",
                "resources/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css",
                "resources/assets/vendor/libs/apex-charts/apex-charts.css",
                "resources/assets/vendor/libs/swiper/swiper.css",
                "resources/assets/vendor/css/pages/app-ecommerce-dashboard.css",
                "resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css",
                "resources/assets/vendor/libs/select2/select2.css",
                "resources/assets/vendor/libs/flatpickr/flatpickr.css",
                "resources/assets/vendor/libs/notyf/notyf.css",
                "resources/assets/vendor/libs/animate-css/animate.css",
                "resources/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css",
                "resources/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css",
                "resources/assets/vendor/libs/datatables-buttons-bs5/buttons.bootstrap5.css",
                "resources/assets/vendor/libs/tagify/tagify.css",
                "resources/assets/vendor/libs/animate-css/animate.css",
                "resources/assets/vendor/libs/sweetalert2/sweetalert2.css",
                "resources/assets/vendor/libs/select2/select2.css",
                "resources/assets/vendor/libs/@form-validation/form-validation.css",
                "",

                //user
                "resources/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css",
                "resources/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css",
                "resources/assets/vendor/libs/datatables-buttons-bs5/buttons.bootstrap5.css",
                "resources/assets/vendor/libs/select2/select2.css",
                "resources/assets/vendor/libs/@form-validation/form-validation.css",

                //js
                // "resources/js/app.js",
                "resources/assets/vendor/js/helpers.js",
                "resources/assets/vendor/js/template-customizer.js",
                "resources/assets/js/config.js",
                "resources/assets/vendor/libs/jquery/jquery.js",
                "resources/assets/vendor/libs/popper/popper.js",
                "resources/assets/vendor/js/bootstrap.js",
                "resources/assets/vendor/libs/node-waves/node-waves.js",
                "resources/assets/vendor/libs/@algolia/autocomplete-js.js",
                "resources/assets/vendor/libs/pickr/pickr.js",
                "resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js",
                "resources/assets/vendor/libs/hammer/hammer.js",
                "resources/assets/vendor/js/menu.js",
                "resources/assets/js/main.js",
                "resources/assets/vendor/libs/i18n/i18n.js",
                "resources/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js",
                "resources/assets/vendor/libs/apex-charts/apexcharts.js",
                "resources/assets/vendor/libs/swiper/swiper.js",
                "resources/assets/js/app-ecommerce-dashboard.js",
                "resources/assets/vendor/libs/cleave-zen/cleave-zen.js",
                "resources/assets/vendor/libs/moment/moment.js",
                "resources/assets/vendor/libs/flatpickr/flatpickr.js",
                "resources/assets/vendor/libs/select2/select2.js",
                "resources/assets/vendor/libs/notyf/notyf.js",
                "resources/assets/js/ui-toasts.js",
                "resources/assets/vendor/libs/moment/moment.js",
                "resources/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js",
                "resources/assets/vendor/libs/sweetalert2/sweetalert2.js",
                "resources/assets/vendor/libs/tagify/tagify.js",
                "resources/assets/vendor/libs/cleave-zen/cleave-zen.js",
                "resources/assets/vendor/libs/select2/select2.js",
                "resources/assets/vendor/libs/@form-validation/popular.js",
                "resources/assets/vendor/libs/@form-validation/bootstrap5.js",
                "resources/assets/vendor/libs/@form-validation/auto-focus.js",
                "resources/assets/js/modal-edit-user.js",
                "resources/assets/js/app-user-view.js",
                "resources/assets/js/app-user-view-account.js",
                "resources/assets/vendor/libs/masonry/masonry.js",
                "resources/js/sweetalert.js",

                //USER
                "resources/assets/vendor/libs/moment/moment.js",
                "resources/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js",
                "resources/assets/vendor/libs/select2/select2.js",
                "resources/assets/vendor/libs/@form-validation/popular.js",
                "resources/assets/vendor/libs/@form-validation/bootstrap5.js",
                "resources/assets/vendor/libs/@form-validation/auto-focus.js",
                "resources/assets/vendor/libs/cleave-zen/cleave-zen.js",
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ["**/storage/framework/views/**"],
        },
    },
});
